### ISSUE TITLE
Seller Page API

### ISSUE THREAD

**Issue by nightknighto** [abdlrhman08/Distributed-project-backend#22]
APIs needed:
Note: all the following endpoints should be local to each seller. The endpoints should not take an input for which seller. Use the JWT sent with the request to get the identity of the seller then display his data.

- [x] 1- Statistics: Endpoint that returns: total items listed count, total products sold count, total revenue, average ratings of all products, how many items out of stock.

- [x] 2- Own Products: Endpoint that returns all the sellers' products, along with quantity sold, stock left, revenue of each item

- [x] 3- Products Low on Stock: Endpoint that returns the products that are low on stock, and stock left for each item.

- [x] 4- Edit Product: Endpoint that takes the item id and data similar to Create Product and edits it in the database.

- [x] 5- Delete Product: Endpoint that takes the item id and delete the item.

![Image](https://github.com/abdlrhman08/Distributed-project-backend/assets/52013393/0fb21fb1-3c7f-4987-801d-31ef0acca5b5)

![Image](https://github.com/abdlrhman08/Distributed-project-backend/assets/52013393/867e4c84-b5e8-4ff3-8c40-3cd829c4e4f9)

**Comment by abdlrhman08** [comment]
Merged in #25
